spring.application.name=MovieTicketBookingSystem

spring.datasource.url=${DB_URL}
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.servlet.context-path=/api/v1.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.Dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret.key = ${SECRET_KEY}